config/routes.rb
DemoApp::Application.routes.draw do

  get "sessions/new"
  get "users/new"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :wishlistlines, :except => [:index, :show] 
  resources :wishlists
  resources :users do
    member do
      get :following, :followers
    end
  end

  root :to => 'pages#home'

end

app/models/wishlistline.rb
class Wishlistline < ActiveRecord::Base
  attr_accessible :bought, :name, :price, :quantity, :wishlist_id
  
  belongs_to :wishlist
  
  validates :name, :length => { :within => 3..50 }
  validates :quantity, :presence => true
  validates :price, :presence => true
end

app/controllers/wishlistlines_controller.rb
class WishlistlinesController < ApplicationController
before_filter :authenticate,    :except => [:new]
before_filter :authorized_user, :only => [:edit, :update, :destroy, :show]


  # GET /wishlistlines/1
  # GET /wishlistlines/1.json
  def show
    @wishlistline = Wishlistline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wishlistline }
    end
  end

  # GET /wishlistlines/1/edit
  def edit
    @wishlistline = Wishlistline.find(params[:id])
  end

  # POST /wishlistlines
  # POST /wishlistlines.json
  def create
    @wishlistline = Wishlistline.new(params[:wishlistline])

    respond_to do |format|
      if @wishlistline.save
        format.html { redirect_to @wishlistline.wishlist, notice: 'Wishlistline was successfully created.' }
        format.json { render json: @wishlistline, status: :created, location: @wishlistline }
      else
        format.html { redirect_to @wishlistline.wishlist, notice: 'Wishlistline was not created.' }
        format.json { render json: @wishlistline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wishlistlines/1
  # PUT /wishlistlines/1.json
  def update
    @wishlistline = Wishlistline.find(params[:id])

    respond_to do |format|
      if @wishlistline.update_attributes(params[:wishlistline])
        format.html { redirect_to @wishlistline, notice: 'Wishlistline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wishlistline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlistlines/1
  # DELETE /wishlistlines/1.json
  def destroy
    @wishlistline = Wishlistline.find(params[:id])
    @wishlistline.destroy

    respond_to do |format|
      format.html { redirect_to @wishlistline.wishlist }
      format.json { head :no_content }
    end
  end
  
  private
  def authorized_user
    @wishlistline = Wishlistline.find(params[:id])
    redirect_to root_path unless current_user?(@wishlistline.wishlist.user)
  end
end

app/helpers/wishlistlines_helper.rb
module WishlistlinesHelper
end

app/views/wishlistlines/_form.html.erb
<%= form_for(@wishlistline) do |f| %>
  <% if @wishlistline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlistline.errors.count, "error") %> prohibited this wishlistline from being saved:</h2>

      <ul>
      <% @wishlistline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :bought %><br />
    <%= f.number_field :bought %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlistlines/_wishlistline.html.erb
<tr class="<%= cycle("even_row", "odd_row") %>" >
  <td class="name">
    <%= best_in_place(wishlistline, :name) %>
  </td>
  <td class="quantity">
    <%= best_in_place(wishlistline, :quantity) %>
  </td>  
  <td class="bought">
    <%= best_in_place(wishlistline, :bought) %>
  </td> 
    <td class="price">
    <%= number_to_currency(best_in_place(wishlistline, :price), :locale => :fr) %>
  </td> 

  <% if current_user?(wishlistline.wishlist.user) %>
    <td>
      <%= link_to "delete", wishlistline, :method => :delete,
        :confirm => "You sure?",
        :title => wishlistline.name %>
    </td>
  <% end %>
  
</tr>

app/views/wishlistlines/edit.html.erb
<h1>Editing wishlistline</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlistline %> |
<%= link_to 'Back', wishlist_path(@wishlistline.wishlist) %>

app/views/wishlistlines/show.html.erb
<p>
  <b>Name:</b>
  <%= @wishlistline.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @wishlistline.quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @wishlistline.price %>
</p>

<p>
  <b>Bought:</b>
  <%= @wishlistline.bought %>
</p>

<p>
  <b>Wishlist:</b>
  <%= @wishlistline.wishlist_id %>
</p>


<%= link_to 'Edit', edit_wishlistline_path(@wishlistline) %> |
<%= link_to 'Back', wishlist_path(@wishlistline.wishlist) %>