config/routes.rb
DemoApp::Application.routes.draw do

  get "sessions/new"
  get "users/new"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :wishlistlines, :except => [:index, :show] 
  resources :wishlists
  resources :users do
    member do
      get :following, :followers
    end
  end

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
  <div id="footer" class="shadow">
    <%= debug(params) if Rails.env.development? %> 
  </div>

app/views/layouts/_navigation.html.erb
  <div id="navigation" class="shadow">
    <% logo = image_tag("rails.png", :alt => "Sample App", :class => "round") %>
    <%= link_to logo, root_path %>
    <nav class="round">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        
        <br />
        
        <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Wishlists", wishlists_path %></li>
          <br />
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Sign out", signout_path %></li>
        <% else %>
          <li><%= link_to "Register", signup_path %></li>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  
  <%= render 'layouts/navigation' %>
  
  <div id="content" class="shadow">
    <% flash.each do |key, value| %>
      <div class="flash shadow <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>

</div>

</body>
</html>